### ISSUE TITLE
Rive models do not render inside collections created at runtime

### ISSUE THREAD

**Issue by igorskugar** [defold/extension-rive#36]
For some reason the only rive model that shows up for me is the one I explicitly dragged into the main game collection.
Other rive models do not render at all when spawned via `collectionproxy` or `collectionfactory`.
I can see those models only inside the editor but after `Cmd + B` they are missing.

Main game collection viewed inside editor:
<img src="https://user-images.githubusercontent.com/5592468/138494626-0ddac275-f926-484f-9401-a86a06820234.png" width="395">

Battle collection (loaded as a proxy) viewed inside editor:
<img src="https://user-images.githubusercontent.com/5592468/138494727-730db9cd-d936-4618-b431-2a3524e2a3d6.png" width="395">

In game (after Cmd + B):
<img src="https://user-images.githubusercontent.com/5592468/138495048-2b30def3-c3fa-48ff-98ff-4dbe0b2a18a6.png" width="392">

As you can see, there is only one health bar rendered and it's the main game collection one.
There should also be one health bar spawned dynamically per character on the map, but unfortunately no bars can be seen even if I put the bar inside the character's collection manually.

I tried to play with z-index values but to no avail.

**Comment by igorskugar** [comment]
@britzl Sample game is working for me and I think I've narrowed down to real bug now.
In my game I was spawning collections (.collection files) with `collectionfactory.create()`.
In the example game you are spawning game objects (.go files) with `factory.create()`.
When I changed my approach to spawning game objects (instead of collections) I ended up with this:
<img src="https://user-images.githubusercontent.com/5592468/139576652-6089cb3e-957f-484c-9144-d966c32c7676.png" width="362" height="293">
The character on the right is a part of the "level" collection loaded with collectionproxy, 
and as you can see, any character spawned inside doesn't have the health bar visible (health bar is a rive model).
The character on the left that has its health bar visible was spawned directly into the main game collection.

Bug: rive models inside `collectionproxy` are not rendered at all (no matter if spawned dynamically or just added manually to the collection).

**Comment by dwnu** [comment]
I think I have the same problem. Everything works as expected when I just put GO with Rive on my first scene. 
When I switch to another scene at runtime (using collectionproxy), a Rive model is never rendered there.
