### ISSUE TITLE
Anti-aliasing

### ISSUE THREAD

**Issue by britzl** [defold/extension-rive#37]
Rive models are currently not rendered with anti-aliasing enabled

**Comment by astrochili** [comment]
A very important moment to start using Rive with Defold.

**Comment by ekt-** [comment]
I'm using .riv files for static background images in defold scenes. it's especially great with gradients. less kb than textures and reduced color banding. the absence of antialiasing unfortunately spoils everything. I think it would be very important for the image quality

**Comment by JCash** [comment]
The best solution is to wait for their next-next version of rive-cpp, which solves it altogether.
In the meantime, it's possible we may add some intermediary solution.

**Comment by JCash** [comment]
Fixed in [2.0.0](https://github.com/defold/extension-rive/releases/tag/2.0.0)
See https://forum.defold.com/t/updated-rive-extension/75169
