### ISSUE TITLE
Rive assets filled black

### ISSUE THREAD

**Issue by bedryck** [defold/extension-rive#44]
### Expected behavior
Rive assets filled correct colors

### Actual behavior
Rive assets filled black

### Steps to reproduce
1) Add https://github.com/defold/extension-rive/archive/main.zip as a dependency.
2) Fetch libraries
3) Change render file to rive.render
4) Create rivescene file and add your rive file.
5) Add rivemodel to the main scene, select default animation. 

<hr/>

> My .rive file and .rivescene in zip file.
[ball.zip](https://github.com/defold/extension-rive/files/7748382/ball.zip)

> How animation looks in rive app.
![image](https://user-images.githubusercontent.com/22659468/146844241-a6833d92-6151-41d5-92df-3e28250f06de.png)

> How looks my .rivescene
![image](https://user-images.githubusercontent.com/22659468/146844332-6e3edad1-9051-4dca-928c-a010de21dd23.png)

> How looks build. Animation plays but fill black
![image](https://user-images.githubusercontent.com/22659468/146844455-df535e7d-3d6f-4dc6-9c3f-e12a0a115ae7.png)
<table>
<tr><td>Build time</td><td>2021-12-16T14:45:33.859978</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>09da5fbf86f611727c6f533a6078c0d84f6b8da9</td></tr>
<tr><td>Defold engine sha</td><td>d31d6397a72178541a5ef6e7ef2bed090d828f58</td></tr>
<tr><td>Defold version</td><td>1.2.190</td></tr>
<tr><td>GPU</td><td>NVIDIA GeForce RTX 2060 SUPER/PCIe/SSE2</td></tr>
<tr><td>GPU Driver</td><td>4.6.0 NVIDIA 472.12</td></tr>
<tr><td>Java version</td><td>11.0.1+13</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>OS name</td><td>Windows 10</td></tr>
<tr><td>OS version</td><td>10.0</td></tr>
<table>

**Comment by britzl** [comment]
Partially fixed in https://github.com/defold/extension-rive/commit/5250ddfc31bff9ea1b0913b1b59b6fce8056ad68

Forum: https://forum.defold.com/t/rive-assets-filled-black-color/69966

"the stroke in the middle isn’t 100% correct, it’s using a blend mode on the layer that we don’t have support for yet. I’ll have to look into that"

**Comment by bedryck** [comment]
Hi, I got the last extension changes. 
![image](https://user-images.githubusercontent.com/22659468/148259899-4e7fec82-22ba-400b-aba4-c391ccc4e7fa.png)

But I have an error when trying to build a game:
```
/defold-rive/src/comp_rive.cpp
	Line 467: unused variable 'color' [-Wunused-variable]
                const float* color                     = &draw_entry_paint.m_Colors[0];
                             ^
	Line 557: unused variable 'ro_index' [-Wunused-variable]
        uint32_t ro_index = world->m_RenderObjects.Size();
                 ^
	Line 567: unused variable 'vb_end' [-Wunused-variable]
        RiveVertex* vb_end = vb_begin;
                    ^
	Line 578: unused variable 'ix_end' [-Wunused-variable]
        int* ix_end   = ix_begin;
             ^
	Line 712: unused variable 'ctx' [-Wunused-variable]
        rive::HContext ctx       = world->m_Ctx->m_RiveContext;
                       ^
	Line 819: unused variable 'renderMode' [-Wunused-variable]
        rive::RenderMode renderMode = rive::getRenderMode(world->m_Ctx->m_RiveContext);
                         ^
	Line 1341: use of undeclared identifier 'ComponentTypeGetContext'
        CompRiveContext* rivectx = (CompRiveContext*)ComponentTypeGetContext(type);
                                                     ^
	Line 1375: unused variable 'go_pos' [-Wunused-variable]
        dmVMath::Point3 go_pos = dmGameObject::GetPosition(component->m_Instance);
                        ^
	Line 1419: unused variable 'bone' [-Wunused-variable]
            dmRive::RiveBone* bone = data->m_Bones[i];
                              ^
	Line 1494: C++ requires a type specifier for all declarations
DM_DECLARE_COMPONENT_TYPE(ComponentTypeRive, "rivemodelc", dmRive::ComponentTypeCreate, dmRive::ComponentTypeDestroy);
^
	Line 1494: too many arguments provided to function-like macro invocation
DM_DECLARE_COMPONENT_TYPE(ComponentTypeRive, "rivemodelc", dmRive::ComponentTypeCreate, dmRive::ComponentTypeDestroy);
                                                                                        ^
	Line 1494: macro 'DM_DECLARE_COMPONENT_TYPE' defined here
    #define DM_DECLARE_COMPONENT_TYPE(symbol, name, type_create_fn) \
                 

```
          
![image](https://user-images.githubusercontent.com/22659468/148260460-3992a217-5654-4452-88c0-4b28d6ba9c8b.png)
![image](https://user-images.githubusercontent.com/22659468/148260503-3582271f-32c0-44b8-ab39-c81249b0efb0.png)

Do I need to wait a little bit for the final result? 
Thank you!

**Comment by JCash** [comment]
Which version are you using?

The master branch is for 1.2.191 Beta currently.

https://github.com/defold/extension-rive/releases/tag/0.9.0 is probably the one you want.
We always recommend our users to use a specific version.

That way we can continue working on newer features, and our users won't get surprised when the master version changes.

**Comment by bedryck** [comment]
Oh, my bad. I will try tomorrow. Thank you!
