### ISSUE TITLE
Rive animations are very slow in the HTML5 engine

### ISSUE THREAD

**Issue by noinskit** [defold/extension-rive#47]
Rive animations seem to slow down the whole program a lot in the HTML5 engine. It's visible even in the sample-rive-game. I tested on Mac OS in Chrome and Safari (the latter seems a bit faster, but still unusable), also using a release build.

I realize that maybe it's a known limitation - in that case a pointer to the roadmap and/or whether it's an inherent limitation or just a matter of priorities would be great! Having used Rive state machines, I just don't want to have to go back to sprites :(

**Comment by JCash** [comment]
This will be fixed in the upcoming release for Defold 1.4.3 (available for testing using the `jni-refactor` branch)

**Comment by britzl** [comment]
We're using the new renderer now, making this issue obsolete. We do however still need to make the renderer work on HTML5 :-)
