### ISSUE TITLE
Rounded joins don't render at the start of a path

### ISSUE THREAD

**Issue by Makoren** [defold/extension-rive#48]
Here's what my design looks like in Rive:

![Screen Shot 2022-03-07 at 3 21 48 pm](https://user-images.githubusercontent.com/37968413/156967607-546f60e8-db4c-459f-a009-e044b433ee9d.png)

And here's the .riv file in Defold:

![Screen Shot 2022-03-07 at 3 22 06 pm](https://user-images.githubusercontent.com/37968413/156967628-6991fba4-b250-48e3-b61c-80fccba37eda.png)

I've noticed this with my other .riv files with rounded corners so I assume it's consistent. I've also tried reversing the direction of the path, which doesn't affect the result.

The other types of stroke joins and caps seem to render correctly.

I'm using the latest version of Defold and the latest stable release of this extension.

**Comment by Jhonnyg** [comment]
Hi, thanks for your report! could you share this repro case with us?

**Comment by Makoren** [comment]
Here's the [Defold project](https://easyupload.io/f2or5w) I was using to reproduce this. It includes the Rive file displayed above, as well as versions of the shape with other join and cap types. Just build and run.

**Comment by JCash** [comment]
Fixed in [2.0.0](https://github.com/defold/extension-rive/releases/tag/2.0.0)
See https://forum.defold.com/t/updated-rive-extension/75169
