### ISSUE TITLE
Strange results with custom shapes

### ISSUE THREAD

**Issue by Makoren** [defold/extension-rive#49]
In Rive, I made a fire animation with a red custom shape, then duplicated that shape to make an extra yellow shape inside it:

![Screen Shot 2022-03-07 at 3 34 39 pm](https://user-images.githubusercontent.com/37968413/156968742-460f3e4d-f5d8-4b19-99e9-425d335ea33b.png)

And here's what it looks like in Defold:

![Screen Shot 2022-03-07 at 3 34 55 pm](https://user-images.githubusercontent.com/37968413/156968768-56a4760f-76fa-4ff6-92ab-03d4282b9869.png)

The red shape stretches to become a rectangle, but the yellow shape stays the same despite being a duplicate of that shape. The yellow shape also isn't rounded properly, and there's a white triangle above the whole design.

I don't understand at all why this is happening, I assume there are parts of the Rive runtime that are incomplete?

Here's a [link to my Rive file](https://github.com/defold/extension-rive/files/8194885/fire.zip). I'm using the latest version of Defold and the latest stable release of the Rive extension.

**Comment by Jhonnyg** [comment]
Hi! It seems to be related to the stroke that is used on the main artboard object, if I remove that it seems to be rendering correctly in the test viewer that is basically using the same code as defold (https://github.com/rive-app/rive-sokol). I haven't tested in Defold actual yet, but I suspect is the same issue. However, it should still work with having a stroke on the main artboard so I'll keep digging into the issue, but in the meanwhile you can bypass it by just removing the stroke.

**Comment by Makoren** [comment]
Thanks, removing the stroke works in my Defold project too. Here's how it looks now:

![Screen Shot 2022-03-13 at 5 06 22 pm](https://user-images.githubusercontent.com/37968413/158047332-d5f574d4-1264-457a-87f3-619ca3d81122.png)

Is there a reason why it's not rounded properly? The bottom of the shape has a lot of edges, rather than being perfectly rounded like in Rive.

**Comment by astrochili** [comment]
@Makoren  Your picture looks like bezier paths isn't supported at the moment?

**Comment by JCash** [comment]
Fixed in [2.0.0](https://github.com/defold/extension-rive/releases/tag/2.0.0)
See https://forum.defold.com/t/updated-rive-extension/75169
