### ISSUE TITLE
Cannot open projects with any Rive model/scene on Windows and Ubuntu

### ISSUE THREAD

**Issue by paweljarosz** [defold/extension-rive#51]
As mentioned here https://forum.defold.com/t/rive-support-alpha-testing/69115/19
I cannot open an example project from this repository - Editor loads and closes abruptly. Last test with Defold alpha 1.3.3.

I tried today on Ubuntu and downloaded the newest alpha (1.3.3) for Linux and extension-rive-main, but the same - I open Defold, select to open game.project from extension-rive-main and it starts to load, but then abruptly closes, before the Editor is opened.

**Comment by britzl** [comment]
I'm not able to reproduce this using 1.3.2 stable or 1.3.3 alpha using macOS. Could you please launch the editor from a terminal and see if you get any additional clues from the log?

**Comment by ghostphoria** [comment]
The same happened to me, but I got an error log
[hs_err_pid5576.log](https://github.com/defold/extension-rive/files/8685196/hs_err_pid5576.log)
.

**Comment by paweljarosz** [comment]
For me, the editor quits abruptly, I terminal though I can see:
[log_extenstion_rive.log](https://github.com/defold/extension-rive/files/8685297/log_extenstion_rive.log)

**Comment by britzl** [comment]
@ghostphoria it looks like you are using Windows. Is this correct?

@paweljarosz and @ghostphoria this happens for you when opening a project using `extension-rive` or when you open the `extension-rive` project itself?

**Comment by paweljarosz** [comment]
For me this happens when I choose to "Open from disk" and select game.project of extension-rive - a loading bar shows for few seconds and then disappear and there is no Defold process nor any popup (on Linux). On Windows there is a popup regarding "OpenJDK Platform binary stopped working".

Also, when I open an empty Defold project, Editor is opened, then I add some rive scene to assets and I try to open it in Editor - instantly closes with no error popup.

**Comment by britzl** [comment]
I can reproduce on Windows.

**Comment by ghostphoria** [comment]
I'm using Windows 10. It's the extension-rive project itself.

**Comment by paweljarosz** [comment]
I did an update today and downloaded a new extension-rive.zip. The same happens, after trying to open a game.project from extension-rive, the loading bars shows for a moment and abruptly quits. Logs (there were only two lines (87 and 88) added after opening the game.project). Ubuntu 20.04.

[editor2.2022-06-20.log](https://github.com/defold/extension-rive/files/8941925/editor2.2022-06-20.log)

**Comment by paweljarosz** [comment]
Still no luck with finding the issue, right? :( Still no running with newest extension and Defold (1.3.4)

**Comment by KL-B0** [comment]
I tried to add the extension-rive to an empty project on Defold 1.3.5.
The editor manages to open, but I get an error telling me the extension is incompatible with this version of the editor.

I'm on Fedora 36, and I managed to extract the log:

[editor.log](https://github.com/defold/extension-rive/files/9585657/editor.log)

The relevant bit seems to be the following:
```
2022-09-16 17:54:06.049 INFO  default    editor.workspace - {:line 330, :msg "Loading plugin defold-rive/editor/src/rive.clj"}
Performance warning, null:437:3 - case has int tests, but tested expression is not primitive.
Performance warning, null:448:3 - case has int tests, but tested expression is not primitive.
2022-09-16 17:54:07.190 ERROR default    editor.workspace - {:line 338, :msg "Exception while loading plugin: Syntax error compiling at (NO_SOURCE_FILE:763:1)."}
```

I tried to downgrade the engine, but it crashes after a while. That's the same situation reported in the other posts.
What can I do to help fix this issue?

**Comment by britzl** [comment]
Thank you everyone for reporting this issue. We are working on an updated renderer that will be much faster and provide textured meshes. I can't guarantee that we'll fix this since the update to the new renderer will make this issue obsolete.

**Comment by KL-B0** [comment]
@britzl do you have a rough estimate of when it will reach release?

**Comment by britzl** [comment]
@KL-B0 we're working on a runtime update and should be done by end of next week.

**Comment by paweljarosz** [comment]
Getting back after some time and updates to extension. I downloaded newest version (tag 0.13.0) - I can open now Rive extension without any problem on Windows, but there is another problem, when trying to run it:

Error: java.lang.AssertionError: Assert failed: Attempting to select nil values
(every? some? node-ids)

And in Build Errors there is:

 /main/bones/bones.collection 
 The file 'null' could not be loaded 
 
 By clicking Report it opens defold's main repo, but I think it is related to extension-rive, but here's the table:
 
 
<table>
<tr><td>Build time</td><td>2023-01-31T13:11:13.422670</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>58bac6dd5a773e01f3a1816bde23283a38e5425d</td></tr>
<tr><td>Defold engine sha</td><td>8cd3a634b13f4db51a37607bf32bf3a3b362c8e6</td></tr>
<tr><td>Defold version</td><td>1.4.2</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/organizations/defold/issues/?query=id%3A"9508674007664f5091502e5893ba72a3"'>9508674007664f5091502e5893ba72a3</a></td></tr>
<tr><td>GPU</td><td>Intel(R) UHD Graphics</td></tr>
<tr><td>GPU Driver</td><td>4.6.0 - Build 27.20.100.8681</td></tr>
<tr><td>Java version</td><td>11.0.15+10-LTS</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>OS name</td><td>Windows 10</td></tr>
<tr><td>OS version</td><td>10.0</td></tr>
<table>

**Comment by JCash** [comment]
The latest version is 1.0 and it's found in the [releases list](https://github.com/defold/extension-rive/releases)

**Comment by JCash** [comment]
Please verify again with the latest release https://github.com/defold/extension-rive/releases/tag/2.0.0
And please read the setup instructions here: https://forum.defold.com/t/updated-rive-extension/75169
