### ISSUE TITLE
[Bug]: Rive extension 0.12.0 not compatible with Defold latest release

### ISSUE THREAD

**Issue by ABDERRAHMANE-OUALI** [defold/extension-rive#53]
when I add dependency for rive extension is shows error of rive extension being not compatible with the editor plugin,
what I do is to install older version (1.31.0)
Is there any solution ?

**Comment by britzl** [comment]
Which version of the editor are you using?

**Comment by maelig-moreau** [comment]
> 

It does the same for me when I use 1.3.5, therefore I have to stay on 1.3.4

**Comment by ABDERRAHMANE-OUALI** [comment]
@maelig-moreau  is defold 1.3.4 work with rive extension 0.12.0 ?

**Comment by ABDERRAHMANE-OUALI** [comment]
@britzl I was using 1.3.5, dual to the issue with the editor plugin I downgrade to 1.3.1

**Comment by britzl** [comment]
@JCash is working on an update of the Rive runtime. The new runtime will be up to date with the Rive tools. Goal is to finish by end of next week.

**Comment by ABDERRAHMANE-OUALI** [comment]
@britzl  ok thanks

**Comment by ABDERRAHMANE-OUALI** [comment]
Fixed with Rive Extension version 0.2.0

**Comment by ABDERRAHMANE-OUALI** [comment]
Fixed with Rive Extension version 0.2.0
