### ISSUE TITLE
Clipping is not working properly with new renderer

### ISSUE THREAD

**Issue by JCash** [defold/extension-rive#56]
The "State" example shows the arrow not being clipped to the box shape.

**Comment by JCash** [comment]
<img width="113" alt="Screenshot 2022-11-08 at 10 46 17" src="https://user-images.githubusercontent.com/1349334/200531577-4f6e11e7-0f94-4fe7-a996-7ca366cccc69.png">

**Comment by Jhonnyg** [comment]
Fixed by https://github.com/defold/extension-rive/commit/590aea589dc66f75674237b6d1b751f7c18c3f85
