### ISSUE TITLE
The car example is not working 100%

### ISSUE THREAD

**Issue by JCash** [defold/extension-rive#57]
Each time it's being rendered, the axles connecting the vehicle with the wheels are shown differently.

**Comment by JCash** [comment]
<img width="319" alt="Screenshot 2022-11-08 at 10 46 46" src="https://user-images.githubusercontent.com/1349334/200531452-19760342-4691-40d3-9c63-5cf5c15a0be7.png">
<img width="325" alt="Screenshot 2022-11-08 at 10 46 34" src="https://user-images.githubusercontent.com/1349334/200531515-a34470c4-b872-496e-85d3-f3341c6a73ab.png">

**Comment by Jhonnyg** [comment]
Fixed by https://github.com/defold/extension-rive/commit/d35f04c108d970ff04fe779d833865aa19a5534f
