### ISSUE TITLE
Extension does not build on HTML5

### ISSUE THREAD

**Issue by Makoren** [defold/extension-rive#64]
Building for HTML5 with the Rive extension installed will throw this error: `Native Library /Volumes/ELEMENTS/dev/Defold/RiveTest/build/plugins/defold-rive/plugins/lib/x86_64-osx/libRiveExt.dylib already loaded in another classloader`

I've tested with DefOS (another native extension) and it builds without issues, so it seems to be exclusive to this extension.

Tested on Defold 1.4.3 alpha, and macOS Ventura 13.1.

**Comment by JCash** [comment]
Which version of the Defold 1.4.3 editor did you use?
Please specify both the editor and engine sha1 from the About box.

**Comment by Makoren** [comment]
Editor SHA1: e6df2106a6f0ffaa1ae220ac1bcb288d303a5e3d
Engine SHA1: e6df2106a6f0ffaa1ae220ac1bcb288d303a5e3d

**Comment by JCash** [comment]
Yeah, this issue is due to our CI not building the editor correctly.
Within 30 minutes, there should be a new release available which handles the .dylib/.so/.dll loading properly.

**Comment by JCash** [comment]
Fixed in latest Defold 1.4.3 alpha: e7abce655d27690816182171ee5f3831b66fda33
