### ISSUE TITLE
Rive models move on their own when more than one model is present

### ISSUE THREAD

**Issue by Makoren** [defold/extension-rive#65]
I've attached a repro case. With no changes, the Rive model animates correctly. But if you add more than one, all models will fly off screen despite no code being attached. The Orthographic Camera library is added to help visualise the issue (set zoom to 0.1).

Interestingly, the game object's position stays the same while this is happening. I have a sprite that updates its position to be the position of one of the bones, but it stays in place while the models fly off screen. The `print` statement also shows this.

This also works with different models. Adding either the `boxman` or `sneksoldier` Rive scenes will produce this bug, but will work fine on their own.

Tested with Defold 1.4.3 alpha, and macOS Ventura 13.1.

[RiveTest.zip](https://github.com/defold/extension-rive/files/10593539/RiveTest.zip)

**Comment by Makoren** [comment]
Reposting this from #64, since I used the same version for this issue:

Editor SHA1: e6df2106a6f0ffaa1ae220ac1bcb288d303a5e3d
Engine SHA1: e6df2106a6f0ffaa1ae220ac1bcb288d303a5e3d

**Comment by JCash** [comment]
Fixed in release 1.0
