### ISSUE TITLE
Add rive_render from rive-sokol as a submodule

### ISSUE THREAD

**Issue by britzl** [defold/extension-rive#8]
We should add rive_render* from rive-sokol as a submodule: https://github.com/rive-app/rive-sokol/tree/master/src/rive

**Comment by JCash** [comment]
To do this, we need to alter the rive-sokol to make it possible to build without libtess2 support, since we don't provide that library for the non-desktop platforms.

**Comment by JCash** [comment]
@britzl Will the "master.zip" etc contain the rive-sokol files?
If not, I think we'll skip this issue, and just rely on copying the relevant files when needed.

**Comment by britzl** [comment]
I agree. Let's just copy the files.
