### ISSUE TITLE
Events not triggering callbacks

### ISSUE THREAD

**Issue by paweljarosz** [defold/extension-rive#91]
The events are not crashing the game anymore, but it seems like I can't make it to be triggering callback. Even in the repro project from the issue, there is no callback called on events.

```lua
 rive.play_state_machine(rive_url, "State Machine 1", {},
    function(self, message_id, message)
        pprint("Hit event", message_id, message)
    end)
```

But nothing in the Console:

![image](https://github.com/defold/extension-rive/assets/11634203/78a91c38-3752-46d6-b929-d08312d5779a)

---

Related (includes package with reproduction project):
https://github.com/defold/extension-rive/issues/89

---

Defold: 1.8.0-beta (1c78e3985d0cb3b257a9968713982d4a5137fb27)
Rive: 0.8.1268
Defold Rive-extension: main

**Comment by britzl** [comment]
Fixed it. The problem was that events were only triggered on event properties. If an event didn't have properties no callback was triggered.
