### ISSUE TITLE
Crash on build

### ISSUE THREAD

**Issue by ChuckMayo** [defold/extension-rive#99]
Editor platform: macOS silicon
Affected Defold Versions: 1.7; 1.8; 1.8.1

Repro steps:
- create empty project
- add rive extension as dependency
- build/bundle from editor
- observe the build error that occurs: `/defold-rive/src/comp_rive.cpp
	Line 189: cast from pointer to smaller type 'uint32_t' (aka 'unsigned int') loses information
        uint32_t index = (uint32_t) params.m_UserData;
                         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~`

[rive-issue-minrepro.zip](https://github.com/user-attachments/files/15672346/rive-issue-minrepro.zip)

**Comment by Jhonnyg** [comment]
Hi, the latest master requires 1.8.2, which is only in alpha release right now. If you want to use rive with an older version you will need to use a specific release. The last release should work, but it usually says which defold version a release is compatible with. I’ll make a note to put this info in the readme

**Comment by ChuckMayo** [comment]
ah that makes sense. I had tried setting it to an older release but I forgot to re-fetch libraries. Thanks, I'll close this then.
